version: "3.3"

services:
  # Collector
  otel-collector:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317" # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - zipkin-all-in-one
      - tempo-query

  # Agent
  otel-agent:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-agent-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "8887:8888" # Prometheus metrics exposed by the agent
      - "14250" # Jaeger grpc receiver
      - "14268" # Jaeger http thrift receiver
      - "55678" # OpenCensus receiver
      - "4317:4317" # OTLP gRPC receiver
      - "9411" # Zipkin receiver
      - "1777:1777" # pprof extension
      - "55679:55679" # zpages extension
      - "13133" # health_check
    depends_on:
      - otel-collector

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Grafana
  grafana:
    image: grafana/grafana:7.3.7
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/datasources
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"

  # Tempo
  tempo:
    image: grafana/tempo:0.5.0
    command:
      [
        "--target=all",
        "--storage.trace.backend=local",
        "--storage.trace.local.path=/var/tempo",
        "--auth.enabled=false",
      ]
    ports:
      - 8081:80

  # Tempo-Query
  tempo-query:
    image: grafana/tempo-query:latest
    #command: ["--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml"]
    environment:
      - BACKEND=tempo:80
    volumes:
      - ./etc/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686" # jaeger-ui
    depends_on:
      - tempo
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"

  # Loki
  loki:
    image: grafana/loki:2.1.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"
